# Generated by Django 6.0.3 on 2026-04-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('salary_min', models.FloatField(blank=True, null=True)),
                ('salary_max', models.FloatField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('job_url', models.URLField(max_length=1000, unique=True)),
                ('site', models.CharField(max_length=100)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
