# Generated by Django 6.0.3 on 2026-04-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_scrapelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapelog',
            name='duplicates_skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapelog',
            name='jobs_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapelog',
            name='source',
            field=models.CharField(default='all', max_length=100),
        ),
    ]
