# Generated by Django 6.0.3 on 2026-04-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_scrapelog_duplicates_skipped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
